In [1]:
f= open("/Users/yeseo/desktop/City_Counted_TaxiMach_Link_Dataset_Full_201709.txt")
s = f.readline()
print (s,type(s))

 <class 'str'>


In [2]:
s = f.readline()
print (s,type(s))

 <class 'str'>


In [3]:
type(s.split(',')[2])

IndexError: list index out of range

In [4]:
if s.split(',')[2]==7469:
    print('----------')

IndexError: list index out of range

In [1]:
a = [0,0,0]
b = [1,2,3]
a
print((type(a) is list)&True,len(a))

True 3


In [6]:
def add_list(x,y):
    if (type(x) is list) & (type(y) is list):
        for i in range(len(x)):
            x[i] += y[i]
        return x

In [7]:
print(add_list(a,b))

[1, 2, 3]


In [8]:
print(type(a))

<class 'list'>


In [11]:
with open("/Users/yeseo/desktop/test_write.txt",'a') as fa:
    for i in range(len(a)):
        fa.write(str(a[i])+',')
    
    fa.write('\n')
    for i in range(len(a)):
        fa.write(str(a[i])+',')
    
    fa.write('\n')
    
    fa.flush()



In [21]:
for i in range(len(a)):
    fw.write(str(a[i])+',')
    
fw.write('\n')


1

In [22]:
fw.flush
for i in range(len(a)):
    fw.write(str(a[i])+',')

In [12]:
for i in range(len(a)):
    fw.write(str(a[i])+',')
    
fw.write('\n')



1

In [1]:
import numpy as np

In [2]:
testx=np.array([7,8,9,10,11,12])
testy=np.array([1,2,3,4,5,6,])

In [5]:
result = testx-testy

In [9]:
abcd = np.hstack((testx[1:],1)) 

In [10]:
abcd

array([ 8,  9, 10, 11, 12,  1])

In [6]:
result

array([6, 6, 6, 6, 6, 6])

In [7]:
e = np.square(result)
print(e)

[36 36 36 36 36 36]


In [8]:
np.mean(e)

36.0

In [10]:
testx*testy

array([ 1,  4,  9, 16, 25, 36])

In [11]:
np.multiply(testx,testy)

array([ 1,  4,  9, 16, 25, 36])

In [13]:
t =np.array( range(0,len(testx)))

In [15]:
np.shape(t)

(6,)

In [18]:
print(testx[t])

[1 2 3 4 5 6]


In [19]:
_x = np.arange(4)
_y = np.arange(5)
_xx, _yy = np.meshgrid(_x, _y)

In [20]:
_xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [21]:
_yy

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [22]:
x,y = _xx.ravel(),_yy.ravel()

In [23]:
x

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [24]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [12]:
top = x + y
bottom = np.zeros_like(top)

NameError: name 'x' is not defined

In [26]:
top

array([0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7])

In [27]:
bottom

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [1]:
testx

NameError: name 'testx' is not defined

In [11]:
for i in range(1,13):
    i = str(i)
    print("now is "+i+"...")

now is 1...
now is 2...
now is 3...
now is 4...
now is 5...
now is 6...
now is 7...
now is 8...
now is 9...
now is 10...
now is 11...
now is 12...


In [13]:
np.array([1,2])

array([1, 2])